sudo: false
language: csharp

# Add build number to version
before_script: sed -ri "s/Version\(\"(.*).0.0\"\)/Version(\"\1.${TRAVIS_BUILD_NUMBER}.0\")/g" OxidePatcher/Properties/AssemblyInfo.cs

# Build the project
solution: OxidePatcher.sln /p:win32Icon="Resources/logo.ico"

# Run deployment script
after_success: "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/OxidePatcher ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "DWK6rjmy/bTeJ4eBcYDjjmjavPVANlHPlh5orhQQNq/kuKHPomvILM4c5rs6h/ajXX7QA1PC0zjdJqdfRxU9lHxP8VWZSq1AIV/aF8nKOQQGKkqjOb6k+hDA0q1UrhzP52cBmJJnOVhZ3mqZGBwzuvDlCNuBMRD/JwongNz8D/k="

env:
  global:
    - secure: "VfJq/lzfekhZ4+gcHig92C2HFXa+0FgQHjTr8GgUHiIkzKp0X6jy+3J6yfTu60ova2zmZkkT8EWW0HTQk4+0zkq2Rk63BJX1yuCUgABwTV1fNmebREp4OQ6GDMMxudmMjgcg+cvO4SokshPtqLPnOeyzSoCfF86G6RVf+UZ6CLM="

deploy:
  provider: releases
  api_key: "914e6b0954a36f11bb77f912e0b6c1ce86a41f49"
  file: "/home/travis/build/OxideMod/OxidePatcher/OxidePatcher/bin/Release/OxidePatcher.exe"
  skip_cleanup: true
  on:
    tags: true
